name: Build Harmony Scripts
on: [push]

jobs:
  Build-Harmony-Scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npx tsc --noCheck
      - uses: actions/upload-artifact@v3
        with:
          name: toonboom-tools
          path: ${{ gitea.workspace }}/dist
